<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="styles\Watc2.TTF" />
    <Resource Include="sprites\icon_buldingmenu.png" />
    <Resource Include="sprites\icon_researchmenu.png" />
    <Resource Include="sprites\icon_trademenu.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="music\*.ogg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="music\*.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
